ejp/urls.py
from main.views import *
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    url(r'^$', 'main.views.home', name="home-page"),

    url(r'^news/(?P<slug>[-\w]+)/$', PostDetailView.as_view(), name='post-detail'),
    url(r'^news/$', PostListView.as_view(), name='post-list'),

    url(r'^events/(?P<slug>[-\w]+)/$', EventDetailView.as_view(), name='event-detail'),
    url(r'^events/$', EventListView.as_view(), name='event-list'),

    url(r'^documents/(?P<slug>[-\w]+)/$', DocumentDetailView.as_view(), name='document-detail'),
    url(r'^documents/$', DocumentListView.as_view(), name='document-list'),

    url(r'^members/(?P<pk>[0-9]+)/$', MemberDetailView.as_view(), name='member-detail'),
    url(r'^members/$', MemberListView.as_view(), name='member-list'),

    url(r'^feedback/$', FeedbackCreateView.as_view(), name='feedback'),
    url(r'^thanks/$', ThanksView.as_view(), name='thanks'),

    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^admin/', include(admin.site.urls)),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
# -*- coding: utf-8 -*-

from django.db import models
from sorl.thumbnail import ImageField
from sorl.thumbnail import get_thumbnail
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django.conf import settings
from django.core.urlresolvers import reverse


# Create your models here.
class Menu(models.Model):
    title = models.CharField(max_length=100)

    def __unicode__(self):
        return self.title

    class Meta:

        verbose_name = "Menu"
        verbose_name_plural = "Menu"


class MenuItem(models.Model):
    menu = models.ForeignKey(Menu)
    title = models.CharField(max_length=100)
    url = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True, verbose_name='Is active')
    position = models.PositiveSmallIntegerField(default=0, verbose_name='Sort position')

    class Meta:
        ordering = ('position',)
        verbose_name = "Menu Item"
        verbose_name_plural = "Menu Items"


class Post(models.Model):
    title = models.CharField(max_length=255)
    content = RichTextField()
    image = ImageField(upload_to='uploads/news/')
    date = models.DateTimeField()
    is_active = models.BooleanField(default=True, verbose_name="Published")
    slug = models.SlugField(unique=True, verbose_name="URL", max_length=255)

    def __unicode__(self):
        return self.title

    def preview(self):
        if self.image:
            im = get_thumbnail(self.image, '100x100', crop='center')
            return '<img src="%s">' % im.url
        return ''

    preview.allow_tags = True

    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    def get_absolute_url(self):
        return reverse("post-detail", kwargs={'slug': self.slug})



class Event(models.Model):
    title = models.CharField(max_length=255)
    content = RichTextField()
    image = ImageField(upload_to='uploads/events/')
    date = models.DateTimeField()
    is_active = models.BooleanField(default=True, verbose_name="Published")
    slug = models.SlugField(unique=True, verbose_name="URL", max_length=255)

    def __unicode__(self):
        return self.title

    def preview(self):
        if self.image:
            im = get_thumbnail(self.image, '100x100', crop='center')
            return '<img src="%s">' % im.url
        return ''

    preview.allow_tags = True

    class Meta:
        verbose_name = "Event"
        verbose_name_plural = "Events"

    def get_absolute_url(self):
        return reverse("event-detail", kwargs={'slug': self.slug})


class Document(models.Model):
    title = models.CharField(max_length=255)
    content = RichTextField()
    date = models.DateTimeField()
    is_active = models.BooleanField(default=True, verbose_name="Published")
    slug = models.SlugField(unique=True, verbose_name="URL", max_length=255)

    def __unicode__(self):
        return self.title

    def preview(self):
        if self.image:
            im = get_thumbnail(self.image, '100x100', crop='center')
            return '<img src="%s">' % im.url
        return ''

    preview.allow_tags = True

    class Meta:
        verbose_name = "Document"
        verbose_name_plural = "Documents"

    def get_absolute_url(self):
        return reverse("document-detail", kwargs={'slug': self.slug})


class Country(models.Model):
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = "Country"
        verbose_name_plural = "Countries"
        ordering = ['name']


class Member(models.Model):
    name = models.CharField(max_length=255)
    country = models.ForeignKey(Country)
    image = ImageField(upload_to='uploads/members', blank=True)
    email = models.EmailField()
    cv = RichTextField(blank=True)

    def __unicode__(self):
        return self.name

    def preview(self):
        if self.image:
            im = get_thumbnail(self.image, '100x100', crop='center')
            return '<img src="%s">' % im.url
        return ''

    preview.allow_tags = True

    class Meta:
        verbose_name = "Member"
        verbose_name_plural = "Members"

    def get_absolute_url(self):
        return reverse("member-detail", kwargs={'pk': self.pk})


class Feedback(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    message = models.TextField()

main/views.py
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.shortcuts import render_to_response
from django.template import RequestContext

from datetime import datetime

from main.models import Post, Event, Document, Member, Feedback, Country


articles_on_page = 8

class PostDetailView(DetailView):
    model = Post


class PostListView(ListView):
    model = Post
    paginate_by = articles_on_page

    def get_queryset(self):
        return Post.objects.filter(date__lte=datetime.now(), is_active=True).order_by('-date')


class EventDetailView(DetailView):
    model = Event


class EventListView(ListView):
    model = Event
    paginate_by = articles_on_page

    def get_queryset(self):
        return Event.objects.filter(date__lte=datetime.now(), is_active=True).order_by('-date')


class DocumentDetailView(DetailView):
    model = Document


class DocumentListView(ListView):
    model = Document
    paginate_by = articles_on_page

    def get_queryset(self):
        return Document.objects.filter(date__lte=datetime.now(), is_active=True).order_by('-date')


class MemberDetailView(DetailView):
    model = Member


class MemberListView(ListView):
    model = Member

    def get_context_data(self, **kwargs):
        context = super(MemberListView, self).get_context_data(**kwargs)
        context['countries'] = Country.objects.all().order_by('name')

        return context


class FeedbackCreateView(CreateView):
    model = Feedback
    fields = ['name', 'email', 'message']
    success_url = '/thanks/'


class ThanksView(TemplateView):
    template_name = "thanks.html"


def home(request):
    news_block = Post.objects.filter(is_active=True, date__lte=datetime.now()).order_by('-date')[:5]
    events_block = Event.objects.filter(is_active=True, date__lte=datetime.now()).order_by('-date')[:4]
    documents_block = Document.objects.filter(is_active=True, date__lte=datetime.now()).order_by('-date')[:5]
    member_block = Member.objects.all().exclude(image='').order_by('?')[:12]

    return render_to_response("index.html", {"news_block": news_block, 'member_block': member_block, 'events_block': events_block, 'documents_block': documents_block}, context_instance=RequestContext(request))

templates/base.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" dir="ltr">
<head>
    <title>{% block title %}{% endblock %} | EJP.EU</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="shortcut icon" href="{% static "favicon.ico" %}" type="image/x-icon"/>
    <link type="text/css" rel="stylesheet" href="{% static "css/ejp.css" %}"/>
    <link type="text/css" rel="stylesheet" href="{% static "css/style_ie.css" %}"/>
    <link type="text/css" rel="stylesheet" href="{% static "css/reset.css" %}"/>
    <link type="text/css" rel="stylesheet" href="{% static "css/lang.css" %}"/>
</head>
<body>
<div class="header">
    <div class="headerin">
        <div class="logo"><a href="/"><img src="{% static "img/logo3.png" %}" width="437" height="160" border="0" alt="EJP.EU"></a></div>
        <div class="dat">
            {% now "D, d M" %}
        </div>
    </div>

</div>
</div>

<div class="headers">
    <div class="shadow"></div>
    <div class="headersin">
        {% for menu_item in menu %}
            {% if forloop.first %}
               <a href="{{ menu_item.url }}" {% if menu_item.url == request.path %}class=active{% endif %}>{{ menu_item.title }}</a>
            {% else %}
                <a href="{{ menu_item.url }}" {% if menu_item.url in request.path %}class=active{% endif %}>{{ menu_item.title }}</a>
            {% endif %}
        {% endfor %}
    </div>
</div>
</div>
<div class="shadow"></div>


{% block content %}{% endblock %}


<div id="footer_bg">
    <div class="shadow"></div>
    <div id="footer">
        <div class="blockbig">
            <div class="blocksmallf2">
                <img style="float:left; margin-top:10px; padding:0 20px 80px;"
                     src="{% static "img/logosmall.png" %}" width="46" height="30" border="0" alt="ejp">
                223 Rue de la Loi 1040 Brussels Belgium<br>
                Tel: +32 2 588 00 89 Fax: +32 2 791 95 50<br>
                <a href="mailto:info@eju.org">info@eju.org</a>
                <br><br>
                <div class="copy">&copy; 2012-{% now "Y" %} EJP, All Rights Reserved</div>

            </div>


        </div>

    </div>
</div>

</body>
</html>

templates/documents-block.html
{% load thumbnail %}
{% if cp_event_block %}
    <h1 class="rubrika"><a href="{% url "document-list" %}">Documents</a></h1>
    {% for article in cp_document_block %}
        <h3><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></h3>
        <hr>
    {% endfor %}
{% endif %}

templates/events-block.html
{% load thumbnail %}
{% if cp_event_block %}
    <h1 class="rubrika"><a href="{% url "event-list" %}">EJP Events</a></h1>
    {% for article in cp_event_block %}
        {% thumbnail article.image "60x33" crop="center" as im %}
            <img src="{{ im.url }}">
        {% endthumbnail %}
        <h3><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></h3>
        <hr>
    {% endfor %}
{% endif %}

templates/index.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Main{% endblock %}

{% block content %}

    <div class="block">
        <div class="blockbig">
            <h1 class="rubrika"><a href=""><a href="{% url "post-list" %}">News</a></a></h1>

            <div class="blockmain">

                {% for article in news_block %}
                    {% if forloop.first %}
                        <div class="teaser">
                            {% thumbnail article.image "274x152" crop="center" as im %}
                                <img src="{{ im.url }}">
                            {% endthumbnail %}

                            <h2><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></h2>
                            {{ article.content|striptags|safe|truncatechars:150 }}
                        </div>
                    {% else %}
                        <div class="newssmall">
                            {% thumbnail article.image "60x33" crop="center" as im %}
                                <img src="{{ im.url }}">
                            {% endthumbnail %}
                            <h3><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></h3>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>


        <div class="blocksmall">
            <h1 class="rubrika"><a href="{% url "event-list" %}">EJP Events</a></h1>

            {% for article in events_block %}
                {% thumbnail article.image "60x33" crop="center" as im %}
                    <img src="{{ im.url }}">
                {% endthumbnail %}

                <h3><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></h3>
                <hr>
            {% endfor %}


            <!--
    <a class="ejp-banner" href="http://jn1.tv/">
    <img src="/sites/default/themes/ejp_theme/img/jn.jpg" alt="" title="" width="310" height="46" />
    </a>
    -->
        </div>
    </div>
    <div class="shadow"></div>
    <div class="block">
        <div class="blockbig">
            <h1 class="rubrika"><a href="{% url "member-list" %}">Members</a></h1>
            {% for member in member_block %}
            <div class="members"><a href="{{ member.get_absolute_url }}">
                {% thumbnail member.image "30x45" crop="center" as im %}
                    <img src="{{ im.url }}">
                {% endthumbnail %} {{ member.name }} </a><br>
                {{ member.country }}
            </div>
            {% endfor %}

        </div>
        <!-- #news_mod-->

        <div class="blocksmall">
            <h1 class="rubrika"><a href="{% url "document-list" %}">Documents</a></h1>
            {% for article in documents_block %}
                <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
                <hr>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/main/document_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}{{ object.title }}{% endblock %}
{% block content %}
    <div class="block">
        <div class="blockbig">
            <h1 class="rubrika"><a href=""></a><a href="{% url "document-list" %}">Documents</a></h1>
            <div id="node-128" class="node">
                <div class="teaser content">

                    <h2>{{ object.title }}</h2>

                    {{ object.content|safe }}
                    <hr>
                </div>
                <div class="clear-block">
                    <div class="meta">
                    </div>

                </div>
            </div>
        </div>
        <div class="blocksmall">
            {% include "news-block.html" %}
            <div class="pad"></div>
            {% include "events-block.html" %}
        </div>
    </div>
{% endblock %}

templates/main/document_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Documents{% endblock %}
{% block content %}
    <div class="block">
        <div class="blockbig">
            <h1 class="rubrika"><a href="">Documents</a></h1>

            {% for article in object_list %}
                <div class="blockmain">
                    <div class="teaser">
                        <h2><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></h2>
                        {{ article.content|striptags|safe|truncatechars:200 }}
                    </div>
                </div>
            {% endfor %}

            {% if is_paginated %}
                <div class="pagination">
                    <span class="page-links">
                        {% if page_obj.has_previous %}
                            <a href="{% url "document-list" %}?page={{ page_obj.previous_page_number }}">&laquo;Previous </a>
                        {% endif %}
                        <span class="page-current">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
                        {% if page_obj.has_next %}
                            <a href="{% url "document-list" %}?page={{ page_obj.next_page_number }}"> Next&raquo;</a>
                        {% endif %}
                    </span>
                </div>
            {% endif %}
        </div>
        <div class="blocksmall">
            {% include "news-block.html" %}
            <div class="pad"></div>
            {% include "events-block.html" %}
        </div>
    </div>
{% endblock %}

templates/main/event_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}{{ object.title }}{% endblock %}
{% block content %}
    <div class="block">
        <div class="blockbig">
            <h1 class="rubrika"><a href=""></a><a href="{% url "event-list" %}">Events</a></h1>


            <div id="node-128" class="node">

                <div class="teaser content">
                    {% thumbnail object.image "274x152" crop="center" as im %}
                        <img src="{{ im.url }}">
                    {% endthumbnail %}

                    <h2>{{ object.title }}</h2>

                    {{ object.content|safe }}
                    <hr>
                </div>

                <div class="clear-block">
                    <div class="meta">
                    </div>

                </div>

            </div>
        </div>
        <div class="blocksmall">
            {% include "news-block.html" %}
            <div class="pad"></div>
            {% include "documents-block.html" %}
        </div>
    </div>
{% endblock %}

templates/main/event_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Events{% endblock %}
{% block content %}
    <div class="block">
        <div class="blockbig">
            <h1 class="rubrika"><a href="">Events</a></h1>

            {% for article in object_list %}
                <div class="blockmain">
                    <div class="teaser">
                        {% thumbnail article.image "274x152" crop="center" as im %}
                            <img src="{{ im.url }}">
                        {% endthumbnail %}

                        <h2><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></h2>
                        {{ article.content|striptags|safe|truncatechars:200 }}
                    </div>
                </div>
            {% endfor %}

            {% if is_paginated %}
                <div class="pagination">
                    <span class="page-links">
                        {% if page_obj.has_previous %}
                            <a href="{% url "event-list" %}?page={{ page_obj.previous_page_number }}">&laquo;Previous </a>
                        {% endif %}
                        <span class="page-current">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
                        {% if page_obj.has_next %}
                            <a href="{% url "event-list" %}?page={{ page_obj.next_page_number }}"> Next&raquo;</a>
                        {% endif %}
                    </span>
                </div>
            {% endif %}
        </div>
        <div class="blocksmall">


            {% include "news-block.html" %}

            <div class="pad"></div>
            {% include "documents-block.html" %}
        </div>
    </div>
{% endblock %}

templates/main/feedback_form.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Feedback{% endblock %}
{% block content %}
    <div class="block">
        <div class="blockbig">
            <div id="node-22" class="node">

                <!-- <span class="submitted">Post on 03/16/2012 - 15:33</span> -->

                <div class="teaser content">
                    <h2>Contact Us</h2>

                    <p>Country: Ukraine<br>
                        City: Kiev<br>
                        Phone: +38 095 444 55 22<br>
                        Fax: +38 095 444 55 22</p>

                    <p>Street: Mechnikova 14/1</p>

                    <form action="" method="post">{% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Submit"/>
                    </form>
                </div>
            </div>
        </div>
        <div class="blocksmall">
            {% include "news-block.html" %}
            <div class="pad"></div>
            {% include "events-block.html" %}
            <div class="pad"></div>
            {% include "documents-block.html" %}
        </div>
    </div>
{% endblock %}

templates/main/member_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}{{ object.name }}{% endblock %}
{% block content %}
    <div class="block">
        <div class="blockbig">
            <h1 class="rubrika"><a href=""></a><a href="{% url "member-list" %}">Members</a> /
                <a href="{% url "member-list" %}#{{ object.country }}">{{ object.country }}</a> /
                <a href="#">{{ object.name }}</a>
            </h1>

            <div class="teaser content membersblog">
                {% thumbnail object.image "274x412" crop="center" as im %}
                        <img src="{{ im.url }}">
                {% endthumbnail %}

                <h2>{{ object.name }}</h2>

                {{ object.cv|safe }}
                <span class="buttonsmall"><a href="{% url "member-list" %}">Back</a></span>
            </div>
            <hr>
        </div>
        <div class="blocksmall">
            {% include "news-block.html" %}
            <div class="pad"></div>
            {% include "events-block.html" %}
            <div class="pad"></div>
            {% include "documents-block.html" %}
        </div>
    </div>
{% endblock %}

templates/main/member_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Members{% endblock %}
{% block content %}
    <div class="block">
        <div class="blockbig">
            <div class="membersblock">
                <div class="memberscol">

                    {% for country in countries %}
                        <h1 class="rubrika"><a name="{{ country.name }}">{{ country.name }}</a></h1>
                        {% for member in country.member_set.all %}
                            <a href="{{ member.get_absolute_url }}">{{ member.name }}</a>

                        {% endfor %}
                        {% if country.name == "Germany" or country.name == "Russia" %}
                            </div>
                            <div class="memberscol">
                        {% endif %}
                    {% endfor %}

                </div>
            </div>
        </div>
        <div class="blocksmall">
            {% include "news-block.html" %}
            <div class="pad"></div>
            {% include "events-block.html" %}
            <div class="pad"></div>
            {% include "documents-block.html" %}
        </div>
    </div>
{% endblock %}

templates/main/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}{{ object.title }}{% endblock %}
{% block content %}
    <div class="block">
        <div class="blockbig">
            <h1 class="rubrika"><a href=""></a><a href="{% url "post-list" %}">News</a></h1>


            <div id="node-128" class="node">

                <div class="teaser content">
                    {% thumbnail object.image "274x152" crop="center" as im %}
                        <img src="{{ im.url }}">
                    {% endthumbnail %}

                    <h2>{{ object.title }}</h2>

                    {{ object.content|safe }}
                    <hr>
                </div>

                <div class="clear-block">
                    <div class="meta">
                    </div>

                </div>

            </div>
        </div>
        <div class="blocksmall">
            {% include "events-block.html" %}
            <div class="pad"></div>
            {% include "documents-block.html" %}
        </div>
    </div>
{% endblock %}

templates/main/post_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}News{% endblock %}
{% block content %}
    <div class="block">
        <div class="blockbig">
            <h1 class="rubrika"><a href="">News</a></h1>

            {% for article in object_list %}
                <div class="blockmain">
                    <div class="teaser">
                        {% thumbnail article.image "274x152" crop="center" as im %}
                            <img src="{{ im.url }}">
                        {% endthumbnail %}

                        <h2><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></h2>
                        {{ article.content|striptags|safe|truncatechars:200 }}
                    </div>
                </div>
            {% endfor %}

            {% if is_paginated %}
                <div class="pagination">
                    <span class="page-links">
                        {% if page_obj.has_previous %}
                            <a href="{% url "post-list" %}?page={{ page_obj.previous_page_number }}">&laquo;Previous </a>
                        {% endif %}
                        <span class="page-current">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
                        {% if page_obj.has_next %}
                            <a href="{% url "post-list" %}?page={{ page_obj.next_page_number }}"> Next&raquo;</a>
                        {% endif %}
                    </span>
                </div>
            {% endif %}
        </div>
        <div class="blocksmall">


            {% include "events-block.html" %}

            <div class="pad"></div>
            {% include "documents-block.html" %}
        </div>
    </div>
{% endblock %}

templates/news-block.html
{% load thumbnail %}
{% if cp_event_block %}
    <h1 class="rubrika"><a href="{% url "post-list" %}">News</a></h1>
    {% for article in cp_news_block %}
        {% thumbnail article.image "60x33" crop="center" as im %}
            <img src="{{ im.url }}">
        {% endthumbnail %}
        <h3><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></h3>
        <hr>
    {% endfor %}
{% endif %}

templates/thanks.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}{{ object.title }}{% endblock %}
{% block content %}
    <div class="block">
        <div class="blockbig">
            <div class="webform-confirmation">
                <p>Thank you, your submission has been received.</p>
            </div>

            <div class="links">
                <a href="/feedback">Go back to the form</a>
            </div>
        </div>
        <div class="blocksmall">
            {% include "news-block.html" %}
             <div class="pad"></div>
            {% include "events-block.html" %}
            <div class="pad"></div>
            {% include "documents-block.html" %}
        </div>
    </div>
{% endblock %}